import { describe, expect, it, vi } from 'vitest';

import {
  crc32,
  decodeFrames,
  decryptPayload,
  encodeFrame,
  TuyaCommand,
} from '../src/main/tuya/TuyaCodec';

/**
 * Fixed vectors, generated by tinytuya — a known-good implementation of this
 * protocol — against the fake key below and checked back through its own
 * decoder. So these assert against the wire format as a real device sees it,
 * not against my reading of the specification.
 *
 * The key is deliberately fake. A real local key must never reach the repo, and
 * it is not needed here: the format does not care which 16 bytes it gets.
 */
const KEY = '0123456789abcdef';

const VECTORS = {
  /** No version header: sending one makes the device answer nothing at all. */
  dpQuery: {
    hex:
      '000055aa000000010000000a00000028e85dd832581fe4732bedd0efe0450ac9' +
      'd5771a557f6d615345a65f08d539b1728575df6e0000aa55',
    text: '{"gwId":"dev1","devId":"dev1"}',
  },
  /** CONTROL is the one command that carries the "3.3" header in the clear. */
  control: {
    hex:
      '000055aa000000010000000700000067332e33000000000000000000000000f3' +
      '6f3bf3e082b0e0638499f4fd3402c5012eea3a0f92a31c78edff31ddfdb02514' +
      '289c9042f2aa08005786aab66fcc6dd2aabe6f348ff0b442995f5c9f24d0ec37' +
      '7222e061a924c591cd9c27ea163ed45fe134bc0000aa55',
    text: '{"devId":"dev1","uid":"dev1","t":"1700000000","dps":{"20":true}}',
  },
  heartbeat: {
    hex:
      '000055aa000000010000000900000018cb70ddc25a2a2045b4c13084418a9abb' +
      '48b041a90000aa55',
    text: '{}',
  },
  /** A reply carries a four-byte return code ahead of the ciphertext. */
  queryResponse: {
    hex:
      '000055aa000000070000000a0000005c00000000c756271dbf61895af70ee82e' +
      'f0d1b12a3d0d4fd18daff4621a7b5a182cc2ced7d41a39524feedc58cca15113' +
      '705a844259d6295431b8c9f7a5a079e82d394311e22f638b6d0f406dfa2e395f' +
      'bb7d59d268e8d8040000aa55',
    text: '{"dps":{"20":false,"21":"white","22":140,"23":0,"24":"000003e803e8","26":0}}',
  },
  /** What the bulb sends unbidden when a wall switch or the vendor app acts. */
  statusPush: {
    hex:
      '000055aa00000000000000080000002c000000006c43740537c46421392c83bf' +
      'a222a5ee23a505a5f798f0d93e34296ee6a5350680ec88800000aa55',
    text: '{"dps":{"20":true,"22":500}}',
  },
} as const;

const bytes = (hex: string): Buffer => Buffer.from(hex, 'hex');

describe('encodeFrame', () => {
  it('produces the exact bytes a device expects for a query', () => {
    const frame = encodeFrame(TuyaCommand.DP_QUERY, 1, VECTORS.dpQuery.text, KEY);
    expect(frame.toString('hex')).toBe(VECTORS.dpQuery.hex);
  });

  /**
   * The header goes on CONTROL and nothing else. Getting this backwards is the
   * classic way a hand-rolled client ends up talking to a device that simply
   * never replies, with nothing logged anywhere to say why.
   */
  it('prepends the version header to CONTROL', () => {
    const frame = encodeFrame(TuyaCommand.CONTROL, 1, VECTORS.control.text, KEY);
    expect(frame.toString('hex')).toBe(VECTORS.control.hex);
    expect(frame.subarray(16, 19).toString('ascii')).toBe('3.3');
  });

  it('leaves the version header off a query and a heartbeat', () => {
    for (const [command, vector] of [
      [TuyaCommand.DP_QUERY, VECTORS.dpQuery],
      [TuyaCommand.HEART_BEAT, VECTORS.heartbeat],
    ] as const) {
      const frame = encodeFrame(command, 1, vector.text, KEY);
      expect(frame.subarray(16, 19).toString('ascii')).not.toBe('3.3');
    }
  });

  it('matches a heartbeat byte for byte', () => {
    expect(encodeFrame(TuyaCommand.HEART_BEAT, 1, VECTORS.heartbeat.text, KEY).toString('hex'))
      .toBe(VECTORS.heartbeat.hex);
  });

  it('refuses a key that is not sixteen characters', () => {
    expect(() => encodeFrame(TuyaCommand.DP_QUERY, 1, '{}', 'too-short'))
      .toThrowError(/16 characters/);
  });
});

describe('decodeFrames', () => {
  it('reads a reply and its return code', () => {
    const { frames, rest } = decodeFrames(bytes(VECTORS.queryResponse.hex), KEY);

    expect(rest).toHaveLength(0);
    expect(frames).toHaveLength(1);
    expect(frames[0]).toMatchObject({
      seq: 7,
      command: TuyaCommand.DP_QUERY,
      retcode: 0,
      text: VECTORS.queryResponse.text,
    });
  });

  it('reads an unsolicited status push', () => {
    const { frames } = decodeFrames(bytes(VECTORS.statusPush.hex), KEY);

    expect(frames[0]).toMatchObject({
      command: TuyaCommand.STATUS,
      text: VECTORS.statusPush.text,
    });
  });

  it('round-trips what it encodes', () => {
    const frame = encodeFrame(TuyaCommand.CONTROL, 3, VECTORS.control.text, KEY);
    const { frames } = decodeFrames(frame, KEY);

    expect(frames[0]?.text).toBe(VECTORS.control.text);
    expect(frames[0]?.seq).toBe(3);
  });

  /** TCP splits wherever it likes; the caller keeps the remainder for next time. */
  it('holds a partial frame back rather than mangling it', () => {
    const whole = bytes(VECTORS.queryResponse.hex);
    const cut = Math.floor(whole.length / 2);

    const first = decodeFrames(whole.subarray(0, cut), KEY);
    expect(first.frames).toHaveLength(0);
    expect(first.rest).toHaveLength(cut);

    const second = decodeFrames(Buffer.concat([first.rest, whole.subarray(cut)]), KEY);
    expect(second.frames).toHaveLength(1);
    expect(second.rest).toHaveLength(0);
  });

  it('reads several frames arriving in one read', () => {
    const { frames, rest } = decodeFrames(
      Buffer.concat([bytes(VECTORS.queryResponse.hex), bytes(VECTORS.statusPush.hex)]),
      KEY,
    );

    expect(frames.map((f) => f.command)).toEqual([TuyaCommand.DP_QUERY, TuyaCommand.STATUS]);
    expect(rest).toHaveLength(0);
  });

  it('returns a frame and keeps the fragment that followed it', () => {
    const trailing = bytes(VECTORS.statusPush.hex).subarray(0, 20);
    const { frames, rest } = decodeFrames(
      Buffer.concat([bytes(VECTORS.queryResponse.hex), trailing]),
      KEY,
    );

    expect(frames).toHaveLength(1);
    expect(rest).toHaveLength(trailing.length);
  });

  /** A corrupt read must not stall the stream on a byte that cannot start a frame. */
  it('resynchronises past leading rubbish', () => {
    const { frames } = decodeFrames(
      Buffer.concat([Buffer.from([0x00, 0xff, 0x13]), bytes(VECTORS.queryResponse.hex)]),
      KEY,
    );

    expect(frames).toHaveLength(1);
  });

  it('drops a frame whose checksum does not match, and carries on', () => {
    const warn = vi.spyOn(console, 'warn').mockImplementation(() => undefined);
    const broken = bytes(VECTORS.queryResponse.hex);
    broken.writeUInt32BE(0xdeadbeef, broken.length - 8);

    const { frames } = decodeFrames(Buffer.concat([broken, bytes(VECTORS.statusPush.hex)]), KEY);

    expect(warn).toHaveBeenCalledOnce();
    expect(frames.map((f) => f.command)).toEqual([TuyaCommand.STATUS]);
    warn.mockRestore();
  });
});

describe('decryptPayload', () => {
  /** A wrong key is indistinguishable from garbage, and never fixes itself. */
  it('reports a wrong key as Unauthorized so the caller stops retrying', () => {
    const frame = bytes(VECTORS.queryResponse.hex);
    expect(() => decodeFrames(frame, 'ffffffffffffffff')).toThrowError(/decrypt/);
    try {
      decodeFrames(frame, 'ffffffffffffffff');
    } catch (error) {
      expect(error).toMatchObject({ code: 'Unauthorized' });
    }
  });

  it('treats an empty body as an empty string rather than failing', () => {
    expect(decryptPayload(Buffer.alloc(0), KEY)).toBe('');
  });
});

describe('crc32', () => {
  /** Cross-checked against zlib.crc32, which is what the device uses. */
  it('matches the standard for known inputs', () => {
    expect(crc32(Buffer.from('123456789', 'ascii'))).toBe(0xcbf43926);
    expect(crc32(Buffer.alloc(0))).toBe(0);
  });
});
