#!/usr/bin/env bash
# Builds the WidgetKit extension and embeds it into the packaged app.
#
# The extension is assembled by hand rather than through an Xcode project: it is a
# single Swift file, and a .appex is just a bundle with an Info.plist and one
# executable. This keeps the whole build reproducible from the command line.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="${1:?usage: build-widget.sh <path to the packaged .app>}"

# identity.json is the single source of truth the Electron side reads too, so the
# App Group and the helper name cannot drift out of sync here. A mismatch fails
# silently: the widget would just read an empty container forever.
id() { node -p "require('$ROOT/identity.json').$1"; }

PRODUCT_NAME="$(id productName)"
TEAM_ID="${LUMEN_TEAM_ID:-$(id teamId)}"
BUNDLE_ID="$(id bundleId)"
WIDGET_KIND="$(id widgetKind)"
RELOAD_HELPER="$(id reloadHelper)"
APP_GROUP="$TEAM_ID.$BUNDLE_ID"
WIDGET_ID="${BUNDLE_ID}.widget"
NAME="$(id widgetName)"
BUILD="$ROOT/widget/.build"
APPEX="$BUILD/$NAME.appex"
GENERATED="$ROOT/widget/Generated"

rm -rf "$BUILD"
mkdir -p "$APPEX/Contents/MacOS" "$GENERATED"

# Swift cannot read identity.json at compile time, so it gets a generated
# constant instead. Regenerated on every build, never edited by hand.
cat > "$GENERATED/Identity.swift" <<SWIFT
// Generated by widget/build-widget.sh from identity.json — do not edit.
enum AppIdentity {
    static let productName = "$PRODUCT_NAME"
    static let appGroup = "$APP_GROUP"
    static let widgetKind = "$WIDGET_KIND"
}
SWIFT

SDK="$(xcrun --sdk macosx --show-sdk-path)"
TARGET="arm64-apple-macos14.0"
SOURCES=(
  "$GENERATED/Identity.swift"
  "$ROOT/widget/LumenWidget.swift"
  "$ROOT/widget/HueBridgeClient.swift"
)

# Xcode writes this list into DerivedData; it is not shipped with the toolchain,
# so building outside Xcode means providing it. It tells the compiler which
# protocol conformances to record for the AppIntents metadata step below.
cat > "$BUILD/const-protocols.json" <<'JSON'
["AppEntity","AppEnum","AppIntent","AppShortcutsProvider","DynamicOptionsProvider",
 "EntityPropertyQuery","EntityQuery","IndexedEntity","PersistentlyIdentifiable",
 "TransientAppEntity","URLRepresentableEntity","URLRepresentableEnum",
 "URLRepresentableIntent","AssistantIntent","AssistantEntity","AssistantEnum"]
JSON

# Two passes over the same sources. The first only harvests the AppIntents
# conformances — the compiler emits them when compiling to an object file, but
# silently skips the step on a run that also links, which is why this cannot be
# folded into the pass below. Without the resulting metadata the widget renders
# its buttons and every tap is a no-op.
xcrun swiftc -sdk "$SDK" -target "$TARGET" -parse-as-library -O -wmo -c \
  -emit-const-values-path "$BUILD/$NAME.swiftconstvalues" \
  -Xfrontend -const-gather-protocols-file -Xfrontend "$BUILD/const-protocols.json" \
  "${SOURCES[@]}" -o "$BUILD/$NAME.o"

# App extensions must enter through NSExtensionMain, not the ordinary Swift main.
# Xcode does this via "-e _NSExtensionMain"; without it the bundle registers in
# pluginkit but never appears in the widget gallery, because the process does not
# behave as an extension at all.
xcrun swiftc -sdk "$SDK" -target "$TARGET" -parse-as-library -O \
  -framework Foundation \
  -Xlinker -e -Xlinker _NSExtensionMain \
  "${SOURCES[@]}" -o "$APPEX/Contents/MacOS/$NAME"

VERSION="$(node -p "require('$ROOT/package.json').version")"

# Xcode normally injects this build metadata. Assembling the bundle by hand means
# writing it ourselves — and without CFBundleSupportedPlatforms and the DT* keys
# the widget gallery ignores the extension even though pluginkit registers it.
SDK_VERSION="$(xcrun --sdk macosx --show-sdk-version)"
SDK_BUILD="$(xcrun --sdk macosx --show-sdk-build-version)"
XCODE_BUILD="$(xcodebuild -version | tail -1 | awk '{print $3}')"
XCODE_VERSION="$(xcodebuild -version | head -1 | awk '{print $2}')"
XCODE_DT="$(echo "$XCODE_VERSION" | awk -F. '{printf "%d%d%d", $1, $2, ($3==""?0:$3)}')"
OS_BUILD="$(sw_vers -buildVersion)"

cat > "$APPEX/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key><string>en</string>
  <key>CFBundleDisplayName</key><string>$PRODUCT_NAME</string>
  <key>CFBundleExecutable</key><string>$NAME</string>
  <key>CFBundleIdentifier</key><string>$WIDGET_ID</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleName</key><string>$NAME</string>
  <key>CFBundlePackageType</key><string>XPC!</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundleVersion</key><string>$VERSION</string>
  <key>CFBundleSupportedPlatforms</key><array><string>MacOSX</string></array>
  <key>BuildMachineOSBuild</key><string>$OS_BUILD</string>
  <key>DTCompiler</key><string>com.apple.compilers.llvm.clang.1_0</string>
  <key>DTPlatformBuild</key><string>$SDK_BUILD</string>
  <key>DTPlatformName</key><string>macosx</string>
  <key>DTPlatformVersion</key><string>$SDK_VERSION</string>
  <key>DTSDKBuild</key><string>$SDK_BUILD</string>
  <key>DTSDKName</key><string>macosx$SDK_VERSION</string>
  <key>DTXcode</key><string>$XCODE_DT</string>
  <key>DTXcodeBuild</key><string>$XCODE_BUILD</string>
  <key>LSMinimumSystemVersion</key><string>14.0</string>
  <!-- macOS 15+ gates local-network access behind user consent; without a purpose
       string the request is denied outright rather than prompted for. -->
  <key>NSLocalNetworkUsageDescription</key>
  <string>$PRODUCT_NAME connects to the lighting hubs on your local network to show and change the state of your lighting.</string>
  <key>NSExtension</key>
  <dict>
    <key>NSExtensionAttributes</key>
    <dict><key>NSExtensionPointVersion</key><string>3.0</string></dict>
    <key>NSExtensionPointIdentifier</key><string>com.apple.widgetkit-extension</string>
  </dict>
</dict>
</plist>
PLIST

# WidgetKit refuses to register an unsandboxed extension — confirmed empirically:
# without app-sandbox the .appex simply never appears in pluginkit. And once
# sandboxed, the App Group container is the only channel through which the app can
# hand data to the widget.
cat > "$BUILD/entitlements.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.app-sandbox</key><true/>
  <!-- The widget talks to the bridge itself, so the sandbox has to let it out. -->
  <key>com.apple.security.network.client</key><true/>
  <key>com.apple.security.application-groups</key>
  <array><string>$APP_GROUP</string></array>
</dict>
</plist>
PLIST

# AppIntents metadata — the bundle the system reads to learn that ToggleRoomIntent
# and ToggleAllIntent exist. Xcode runs this as a build phase; assembling by hand
# means running it ourselves, and it has to happen before codesign so the
# signature covers the new resource.
mkdir -p "$APPEX/Contents/Resources"
printf '%s\n' "${SOURCES[@]}" > "$BUILD/sources.txt"
echo "$BUILD/$NAME.swiftconstvalues" > "$BUILD/constvalues.txt"
xcrun appintentsmetadataprocessor \
  --output "$APPEX/Contents/Resources" \
  --toolchain-dir "$(dirname "$(dirname "$(xcrun --find swiftc)")")" \
  --module-name "$NAME" \
  --sdk-root "$SDK" \
  --xcode-version "$XCODE_BUILD" \
  --platform-family macOS \
  --deployment-target 14.0 \
  --target-triple "$TARGET" \
  --source-file-list "$BUILD/sources.txt" \
  --swift-const-vals-list "$BUILD/constvalues.txt" \
  --force

# A silent failure here would ship a widget whose buttons do nothing at all.
test -f "$APPEX/Contents/Resources/Metadata.appintents/extract.actionsdata" \
  || { echo "missing AppIntents metadata — the widget buttons would be dead" >&2; exit 1; }

IDENTITY_NAME="${LUMEN_IDENTITY:-Developer ID Application}"
IDENTITY="$(security find-identity -v -p codesigning \
  | grep "$IDENTITY_NAME" | head -1 | awk '{print $2}')"
if [ -z "$IDENTITY" ]; then
  echo "no code-signing identity matching: $IDENTITY_NAME" >&2
  exit 1
fi
echo "signing with identity $IDENTITY"
codesign --force --sign "$IDENTITY" --options runtime --timestamp \
  --entitlements "$BUILD/entitlements.plist" "$APPEX"

# Helper the Electron process spawns to tell WidgetKit that state changed; living
# in Contents/MacOS means the call is attributed to the host app.
xcrun swiftc -sdk "$SDK" -target arm64-apple-macos14.0 \
  "$ROOT/widget/LumenWidgetReload.swift" -o "$APP/Contents/MacOS/$RELOAD_HELPER"
codesign --force --sign "$IDENTITY" --options runtime --timestamp \
  "$APP/Contents/MacOS/$RELOAD_HELPER"

mkdir -p "$APP/Contents/PlugIns"
rm -rf "$APP/Contents/PlugIns/$NAME.appex"
cp -R "$APPEX" "$APP/Contents/PlugIns/"

# Embedding a new bundle invalidates the app's signature, so the host must be
# re-signed after the extension is dropped in.
codesign --force --sign "$IDENTITY" --options runtime --timestamp \
  --entitlements "$ROOT/build/entitlements.plist" "$APP"

echo "embedded $NAME.appex into $APP"
